### ISSUE TITLE
Missing meta data

### ISSUE THREAD

**Issue by sarigs** [CheckPointSW/QueryOrientedProgramming#1]
Dear Developer, 

 For readability and Search Engine Optimization (SEO) it would be great if you could do the followings:
- [x] Please provide more than 8 words in the "About" field
- [x] Please provide relevant "Topics" 
>**Environment topic examples**:
>azure, aws, gcp
>**Functionality topic examples**:
>**build**, **deploy**, **staging**, **operate**, terraform, ansible, helm, android, cloudguardIaaS, management, gaia, threat-prevention, identity-awareness, smp, iot, cloudguard-connect, cloudguard-dome9, malware, evasion

**Comment by chkp-eyalit** [comment]
Added the needed topics + created an "about" description for the repository. If more changes are needed, feel free to reopen this ticket.
